### ISSUE TITLE
Missing Jordi Anguela's talk

### ISSUE THREAD

**Issue by adrianmo** [tgndevs/meetup#4]
I think we are missing Jordi Anguela's talk about frontend development. @jpahullo or @ryanfox1985 do you have info about this talk?

**Comment by jpahullo** [comment]
The link appears in the meetup site.

**Comment by ryanfox1985** [comment]
Here is the link:
http://www.slideshare.net/JordiAnguela/professionalizing-the-frontend

2016-05-31 12:05 GMT+02:00 Jordi Pujol-Ahulló notifications@github.com:
