### ISSUE TITLE
'How to leverage Docker thanks to Kubernetes' slides

### ISSUE THREAD

**Issue by cmmata** [tgndevs/meetup#7]
Hello all,

I can't see 'How to leverage Docker thanks to Kubernetes' slides, the link points to 'Understanding the different Git workflows'.

**Comment by ryanfox1985** [comment]
I asked to @pipo02mix in slack tgndevs#meetup.

**Comment by ryanfox1985** [comment]
Closed in: https://github.com/tgndevs/meetup/pull/8

**Comment by cmmata** [comment]
:+1: Thanks!
